---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pkpm.
--- DateTime: 2019/1/3 15:37
---

ngx.req.read_body() -- 解析 body 参数之前一定要先读取 body
local arg = ngx.req.get_post_args()
for k,v in pairs(arg) do
    ngx.say("[POST] key:", k, " v:", v)
end

local args = ngx.md5(arg["username"])
ngx.say("md5:",args)
ngx.header.new_field = "token"
ngx.header["token"] = args
ngx.status = ngx.HTTP_CREATED
ngx.exit(201)
