---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pkpm.
--- DateTime: 2019/1/3 16:28
---
-- auth by redis
function auth_redis(username, password)
    local redis_info = {
        host="127.0.0.1",
        port=6379,
        db=0,
        password="mypass"
    }
    local redis = require "resty.redis"
    local red = redis:new()
    red:set_timeout(3000) -- 3 sec
    local ok, err = red:connect(redis_info["host"], redis_info["port"])
    if not ok then
        ngx.log("failed to connect: ", err)
        return false
    end
    local res, err = red:auth(redis_info["password"])
    if not res then
        ngx.log("failed to authenticate: ", err)
        return false
    end
    local res, err = red:hmget(username, "username", "password")
    -- for k, v in ipairs(res) do
    -- 	ngx.say(k)
    -- 	ngx.say(v)
    -- end
    if res and res ~= ngx.null then
        local user = res[1] or ""
        local pass = res[2] or ""
        -- ngx.say("username: " .. user .. " , password: " .. pass)
        if user ~="" and pass ~= "" and  username == user and password == pass then
            -- ngx.log("username: " .. user .. " , password: " .. pass)
            return true
        end
    else
        return false
    end
end
auth_redis("user1","123456")